### PR TITLE
add Chinese Simplified (zh_CN) translation

### PR DESCRIPTION
**Pull request by TylerTemp**
Add Chinese Simplified (zh_CN) translation.

Really love this helpful work :-)

It'd be nice if the client page(the html part) can support localization too :-]

### CODE REVIEW

**Comment by TylerTemp** [comment]
If you're going to merge this pull, could you please also update:(thx)

1. the translation of the app name (can be used in `.desktop` file):

`Name[zh_CN]=Sailfish无线键盘`

2. the description of the app in Jolla Store:

**使用你的电脑键盘在你的手机上打字**

通过这个应用你可以通过电脑键盘在你的手机上打字。

只需要将你的手机和电脑连接到同一个局域网下。在电脑上浏览手机上显示的网址，然后就可以开始打字了。你的键盘输入会被复制到手机剪贴板下，并可以粘贴到应用的任何激活的输入框控件中。

**Comment by abertschi** [comment]
@TylerTemp Thanks for your support. Will be shipping your contribution with the next release. Regarding the localization for the client page, I just created a feature request here #9. So if you have time, feel free to implement any internationalisation support.

**Comment by abertschi** [comment]
@TylerTemp, version v-0.3.0 (1c4b134624caec709d6e9295d20fff8580960c61) contains a redesign of almost all UI elements. I will be heading towards the harbour QA in a couple of days. Because of the redesign, I unfortunately can not use your translations anymore unless you translate them again.

**Comment by TylerTemp** [comment]
Updated :-)

Is the "athor" a typo of "author" (in `About` page, line 62 of `harbour-wlan-keyboard/translations/harbour-wlan-keyboard.ts`)?

**Comment by abertschi** [comment]
It was. Addressed with 4d93e54703ac7ce664488b1b8e172a5552bcb6e0.

**Comment by abertschi** [comment]
Updated tranlsation key author for zh_CN 5c845a0a4d85e388c8ecd737a67150550a2de8ba

**Pull request merged**
